language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
branches:
  only:
    - master
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run report-coverage